### ISSUE TITLE
question about dynamic RGB

### ISSUE THREAD

**Issue by tb2-sy** [hturki/suds#17]
Thank you for sharing the code.
After running your code eval.py, I found that in the result of dynamic rgb of vkitti2 scene, there will be some things other than dynamic vehicles (mostly in static tree areas), what is the reason?

**Comment by hturki** [comment]
Shoot, I knew I forgot something as part of the release.

This is partially due to how transmittance is calcuated - even if "dynamic" sigma values along a ray are low, they will have a high weight when rendering the pixel color RGB if there is no other high-sigma values ahead of them. In practice when rendering visualizations for the paper I'd zero out all of the weights along a ray when rendering the dynamic component when the accumulated DYNAMIC_WEIGHT value fell below a certain threshold.

Other hyperparameters that affect the static-dynamic factorization are the entropy loss term, the dynamic loss term, and the entropy skewness. But I'd probably start with just zeroing out pixels below a certain dynamic threshold when rendering first.
