### ISSUE TITLE
Downsample rate before feature extraction

### ISSUE THREAD

**Issue by rwn17** [hturki/suds#7]
Hello @hturki, I want to express my appreciation for your excellent work! In the paper, you mentioned that you "downsample our images to fit into GPU memory and then upsample with nearest neighbor interpolation." However, I was unable to locate the implementation of this section, so please correct me if I am mistaken. Additionally, I am curious about the specific type and rate of downsampling that was used in the paper. Thank you in advance for your response!

**Comment by hturki** [comment]
The downsampling size is specified here when extracting DINO features: https://github.com/hturki/suds/blob/main/scripts/extract_dino_features.py#L343
The upsampling happens when loading the data at train time: https://github.com/hturki/suds/blob/main/suds/data/image_metadata.py#L97

(I should likely document the data loading code more thoroughly but will probably not have time to do this for a while)

Hope this helps

**Comment by rwn17** [comment]
Thanks! I will close this issue.
